# Generated by Django 5.1.2 on 2025-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=0, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
