# Generated by Django 5.1.2 on 2025-01-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
