# Generated by Django 5.1.2 on 2025-01-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
